show_drafts: false
future: false
lsi: true
highlighter: pygments
permalink: pretty
title: Erik Erwitt
description: I enjoy exploring the world while writing software.
tagline: Software Engineer
url: http://eerwitt.github.io
baseurl: /
author:
  name: e3
  url: https://twitter.com/legoscript
paginate: 5
version: 2.1.0
github:
  repo: https://github.com/eerwitt
markdown: kramdown
